apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deploy
  labels:
    app: financial-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: financial-app
  template:
    metadata:
      labels:
        app: financial-app
    spec:
      containers:
      - name: bankapp-container
        image: paragv14/financial-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-np-service
  labels:
    app: financial-app
spec:
  selector:
    app: financial-app

  type: NodePort
  ports:
  - nodePort: 31030 
    port: 8082
    targetPort: 8082

